spring:
    application:
        name: BringMe
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/test
server:
    port: 8080

---

spring:
    profiles: production
server:
    port: 9000
