spring:
    application:
        name: BringMe
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/bringme
        username: bringme
        password: bringme
server:
    port: 8080
credentials:
  user: bringme
  password: bringme
---

spring:
    profiles: production
server:
    port: 9000
