spring:
    application:
        name: BringMe
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/bringme
        username: bringme
        password: bringme
    social:
        facebook:
            appId: 1753811371523447
            appSecret: e52f7f8deb584fe23de12b3937d5a4d9
server:
    port: 8080
credentials:
  user: bringme
  password: bringme
---

spring:
    profiles: production
server:
    port: 9000
