mysql:
    image: mysql:5.7
    container_name: BringMeMysql
    volumes:
       - "./.data/db:/var/lib/mysql"
    environment:
       MYSQL_ROOT_PASSWORD: bringme
       MYSQL_DATABASE: bringme
       MYSQL_USER: bringme
       MYSQL_PASSWORD: bringme
    ports:
         - "0.0.0.0:3306:3306"